# 空氣污染監測網 網路爬蟲實作練習

能夠利用 selenium + BeautifulSoup 撰寫爬蟲，並存放到合適的資料結構

# 作業目標

根據範例 ，完成以下問題：


① 取出 台北市士林區 2018/01 – 2018/08 的 SO2 資料

② 取出 台北市士林區 2018/01 – 2018/08 的 SO2、CO 資料


# ① 取出 台北市士林區 2018/01 – 2018/08 的 SO2 資料

In [1]:
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from bs4 import BeautifulSoup

browser = webdriver.Chrome('./chromedriver')

browser.get("http://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx")

In [6]:
# 模擬使用者操作行為，選擇/點擊

selectSite = Select(browser.find_element_by_id("ctl05_ddlSite"))
selectSite.select_by_value('11')
selectYear = Select(browser.find_element_by_id("ctl05_ddlYear"))
selectYear.select_by_value('2018')

browser.find_element_by_id('ctl05_btnQuery').click()

In [7]:
# 取得資料，丟到 BeautifulSoup 解析

html_source = browser.page_source

soup = BeautifulSoup(html_source, 'html.parser')
table = soup.find('table', class_='TABLE_G')

In [9]:
# 關閉瀏覽器
browser.quit();

In [69]:
import pandas as pd

dfs = pd.read_html(soup.prettify(), header=0)

In [70]:
SO2 = dfs[5][['監測日期','監測項目','監測值']].copy()
SO2 = SO2[SO2['監測項目'] == 'SO2']
SO2 = SO2.iloc[:8]
SO2 = SO2[['監測日期','監測值']]

In [71]:
SO2

      監測日期  監測值
0  2018/01  1.8
1  2018/02  1.9
2  2018/03  2.2
3  2018/04  2.3
4  2018/05  3.1
5  2018/06  2.7
6  2018/07  2.2
7  2018/08  2.4

# 2. 取出 台北市士林區 2018/01 – 2018/08 的 SO2、CO 資料

In [100]:
SO2CO = dfs[5][['監測日期','監測項目','監測值']].copy()
SO2CO = SO2CO[(SO2CO['監測項目'] == 'SO2') | (SO2CO['監測項目'] == 'CO')]
SO2CO = SO2CO[(SO2CO['監測日期'] < '2018/09')]

In [101]:
SO2CO

       監測日期 監測項目   監測值
0   2018/01  SO2  1.80
1   2018/02  SO2  1.90
2   2018/03  SO2  2.20
3   2018/04  SO2  2.30
4   2018/05  SO2  3.10
5   2018/06  SO2  2.70
6   2018/07  SO2  2.20
7   2018/08  SO2  2.40
12  2018/01   CO  0.34
13  2018/02   CO  0.44
14  2018/03   CO  0.40
15  2018/04   CO  0.38
16  2018/05   CO  0.34
17  2018/06   CO  0.29
18  2018/07   CO  0.21
19  2018/08   CO  0.30